'use strict';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const root=path.resolve(process.argv[2]||path.join(__dirname,'..')),issues=[],skipped=new Set(['.git','node_modules','.sites-checkout','VI-预览']);let scanned=0;
const owner=path.basename(os.homedir()),escape=s=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
const rules=[['personal-home-path',/[A-Za-z]:[\\/]Users[\\/][^\s"'<>\\/]+/i],['private-workspace-path',/(?<![A-Za-z0-9_])[A-Za-z]:[\\/](?!cyka(?:[\\/]|$))[^\s"'<>]+/i],['chat-account-id',/wxid_[a-zA-Z0-9_]+/],['chat-download-path',/[\\/](?:xwechat_files|weichat)[\\/]/i],['embedded-secret',/(?:PRIVATE_KEY|API_SECRET|ACCESS_TOKEN|API_KEY)\s*[:=]\s*["'][a-zA-Z0-9_\-]{24,}["']/i]];
if(owner.length>2)rules.push(['local-user-name',new RegExp('\\b'+escape(owner)+'\\b','i')]);
const textTypes=new Set(['.js','.cjs','.mjs','.json','.html','.css','.md','.txt','.yml','.yaml','.toml','.sol','.bat']);
function walk(directory){for(const e of fs.readdirSync(directory,{withFileTypes:true})){if(skipped.has(e.name))continue;const file=path.join(directory,e.name),relative=path.relative(root,file).replaceAll('\\','/');if(e.isSymbolicLink()){issues.push({file:relative,type:'symlink'});continue;}if(e.isDirectory()){walk(file);continue;}if((e.name==='.env'||/^(?:credentials?|secrets?)\./i.test(e.name)||relative.startsWith('server/uploads/'))){issues.push({file:relative,type:'runtime-or-credential-file'});continue;}if(!textTypes.has(path.extname(e.name))&&e.name!=='.env.example')continue;if(relative.includes('/vendor/'))continue;scanned++;const text=fs.readFileSync(file,'utf8');for(const [type,regex]of rules)if(regex.test(text))issues.push({file:relative,type});}}
walk(root);const report={version:'VI',status:issues.length?'FAIL':'PASS',scope:'Release source and generated public files; exclusions include dependencies, repository metadata and preview screenshots',scannedTextFiles:scanned,issues,valuesPrinted:false,createdAt:new Date().toISOString()};
if(root===path.resolve(__dirname,'..'))fs.writeFileSync(path.join(root,'reports/privacy-VI.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));if(issues.length)process.exitCode=1;
